name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run check
      - run: npm run --workspaces build
      - uses: actions/upload-artifact@v4
        with:
          name: codemirror
          path: packages/codemirror/codemirror-*.vsix
      - uses: actions/upload-artifact@v4
        with:
          name: codemirror-interact
          path: packages/codemirror-interact/codemirror-interact-*.vsix
